#!/usr/bin/python3
import argparse
from lightness.settings.gameoflifesettings import GameOfLifeSettings
from lightness.gameoflife import GameOfLife

def parseArgs():
    parser = argparse.ArgumentParser(description="Conway's game of life.")
    parser.add_argument('--display-width', dest='display_width', action='store', type=int,
        default=GameOfLifeSettings.DEFAULT_DISPLAY_WIDTH, metavar='N', help='Number of pixels / units')
    parser.add_argument('--display-height', dest='display_height', action='store', type=int,
        default=GameOfLifeSettings.DEFAULT_DISPLAY_HEIGHT, metavar='N', help='Number of pixels / units')
    parser.add_argument('--flip-x', dest='flip_x', action='store_true', default=False,
        help='flip X direction output')
    parser.add_argument('--flip-y', dest='flip_y', action='store_true', default=False,
        help='flip Y direction output')
    parser.add_argument('--brightness', dest='brightness', action='store', type=int, default=GameOfLifeSettings.DEFAULT_BRIGHTNESS,
        metavar='N', help='Global brightness value. Max of 31.')
    parser.add_argument('--loop', dest='should_loop', action='store_true', default=False,
        help='Whether to start a new game after game over.')
    parser.add_argument('--seed-liveness-probability', dest='seed_liveness_probability', action='store', type=float,
        default=GameOfLifeSettings.DEFAULT_SEED_LIVENESS_PROBABILITY, metavar='N',
        help='Probability that each pixel is live when seeding.')
    parser.add_argument('--tick-sleep', dest='tick_sleep', action='store', type=float,
        default=GameOfLifeSettings.DEFAULT_TICK_SLEEP, metavar='N',
        help='Amount to sleep after each tick.')
    parser.add_argument('--game-over-detection-lookback', dest='game_over_detection_lookback', action='store', type=int,
        default=GameOfLifeSettings.DEFAULT_GAME_OVER_DETECTION_LOOKBACK, metavar='N',
        help='Number of turns to look back to see if game has not changed (i.e. it is over).')

    args = parser.parse_args()
    return args

args = parseArgs()
settings = GameOfLifeSettings(
    color_mode = None, display_width = args.display_width, display_height = args.display_height,
    brightness = args.brightness, flip_x = args.flip_x, flip_y = args.flip_y, log_level = None,
    seed_liveness_probability = args.seed_liveness_probability, tick_sleep = args.tick_sleep,
    game_over_detection_lookback = args.game_over_detection_lookback,
)
game = GameOfLife(settings)
game.play(should_loop = args.should_loop)
