#!/usr/bin/python3

from http.server import HTTPServer, BaseHTTPRequestHandler
from io import BytesIO
import json
import subprocess
import ssl
from lightness.process import Process
from lightness.db import DB
from lightness.logger import Logger

class LightnessServerRequestHandler(BaseHTTPRequestHandler):

    __db = DB()
    __root_dir = "/home/pi/lightness/htdocs"
    __logger = Logger().set_namespace("LightnessServerRequestHandler")

    def do_GET(self):
        if self.path[:4] == "/api":
            return self.API_GET_REQUEST(self.path[5:])

        if self.path == '/':
            self.path = '/index.html'

        self.path = self.__root_dir + self.path

        ext = self.path[self.path.rfind(".")+1:].lower()

        is_bytes = False
        if ext == 'ico':
            is_bytes = True
        elif ext == 'woff':
            is_bytes = True
        elif ext == 'woff2':
            is_bytes = True
        elif ext == 'ttf':
            is_bytes = True

        try:
            if is_bytes:
                file_to_open = open(self.path, 'rb').read()
            else:
                file_to_open = open(self.path).read()
            self.send_response(200)
        except Exception as e:
            self.__logger.error(str(e))
            file_to_open = "File not found"
            self.send_response(404)

        self.end_headers()

        if is_bytes:
            self.wfile.write(file_to_open)
        else:
            self.wfile.write(bytes(file_to_open, 'utf-8'))

    def API_GET_REQUEST(self, path):
        if (path == 'get_queue'):
            response = self.get_queue()
        else:
            self.send_response(404)
            self.end_headers()
            return

        self.send_response(200)
        self.end_headers()
        resp = BytesIO()
        resp.write(bytes(json.dumps(response), 'utf-8'))
        self.wfile.write(resp.getvalue())

    def get_queue(self):
        response_details = {}
        queue = self.__db.getQueue()
        response_details['queue'] = queue
        response_details['success'] = True
        return response_details

    def do_POST(self):
        content_length = int(self.headers['Content-Length'])
        body = self.rfile.read(content_length)

        post_data = json.loads(body.decode("utf-8"))
        action = post_data['action']
        if (action == 'enqueue'):
            response = self.enqueue(post_data)
        elif (action == 'skip'):
            response = self.skip(post_data)
        elif (action == 'clear'):
            response = self.clear(post_data)
        else:
            self.send_response(404)
            self.end_headers()
            return

        self.send_response(200)
        self.end_headers()
        resp = BytesIO()
        resp.write(bytes(json.dumps(response), 'utf-8'))
        self.wfile.write(resp.getvalue())

    def enqueue(self, post_data):
        url = post_data['url']
        is_color = post_data['color']
        thumbnail = post_data['thumbnail']
        title = post_data['title']

        response_details = {}
        response_details['url'] = url
        response_details['is_color'] = is_color
        response_details['thumbnail'] = thumbnail
        response_details['title'] = title

        self.__db.enqueue(url, is_color, thumbnail, title)

        response_details['success'] = True
        return response_details

    def skip(self, post_data):
        self.__db.skip()

        response_details = {}
        response_details['success'] = True
        return response_details

    def clear(self, post_data):
        self.__db.clear()

        response_details = {}
        response_details['success'] = True
        return response_details

class LightnessServer:

    __secure = False
    __server = None

    def __init__(self, secure=False):
        self.__secure = secure
        if (not self.__secure):
            self.__server = HTTPServer(('0.0.0.0', 80), LightnessServerRequestHandler)
        else:
            self.__server = HTTPServer(('0.0.0.0', 443), LightnessServerRequestHandler)
            self.__server.socket = ssl.wrap_socket (self.__server.socket,
                                            keyfile="/home/pi/.sslcerts/private.key",
                                            certfile='/home/pi/.sslcerts/certificate.crt',
                                            server_side=True)

    def serve_forever(self):
        self.__server.serve_forever()

server = LightnessServer(secure=False)
server.serve_forever()
