#!/usr/bin/python3
import argparse
from lightness.settings import Settings
from lightness.videoplayer import VideoPlayer
from lightness.videoprocessor import VideoProcessor
from lightness.process import Process

import os

def parseArgs():
    parser = argparse.ArgumentParser(description='convert a video.')
    parser.add_argument('--url', dest='url', action='store', default='https://www.youtube.com/watch?v=xmUZ6nCFNoU',
        help='youtube video url. default: The Smashing Pumpkins - Today.')
    parser.add_argument('--display-width', dest='display_width', action='store', type=int, default=28, metavar='N',
        help='Number of pixels / units')
    parser.add_argument('--display-height', dest='display_height', action='store', type=int, default=18, metavar='N',
        help='Number of pixels / units')
    parser.add_argument('--color', dest='is_color', action='store_true', default=False,
        help='color output? (default is black and white)')
    parser.add_argument('--flip-x', dest='flip_x', action='store_true', default=False,
        help='flip X direction output')
    parser.add_argument('--flip-y', dest='flip_y', action='store_true', default=False,
        help='flip Y direction output')
    parser.add_argument('--brightness', dest='brightness', action='store', type=int, default=3, metavar='N',
        help='Global brightness value. Max of 31.')

    args = parser.parse_args()
    return args

process = Process(Process.MODE_WRITE)
process.set_status(Process.STATUS_LOADING)

args = parseArgs()
video_settings = Settings(args)

video_player = VideoPlayer(video_settings)
video_player.clearScreen()

video_processor = VideoProcessor(video_settings, process)
video_processor.process_and_play(url = args.url, video_player = video_player)

process.set_status(Process.STATUS_DONE)
video_player.clearScreen()
