import math
import numpy as np
import random

from pifi.config import Config
from pifi.screensaver.screensaver import Screensaver


class Purkinje(Screensaver):
    """
    Subjective visual phenomena screensaver inspired by Jan Evangelista Purkinje's
    studies of entoptic imagery -- the patterns generated by your own visual system.

    Cycles through four modes drawn from closed-eye and retinal phenomena:

      1. Entoptic lattice  - breathing honeycomb/diamond grid that warps and drifts
      2. Vascular tree     - branching retinal vessel patterns that pulse and regrow
      3. Blue field         - Scheerer's phenomenon: bright dots darting on deep blue
      4. Afterimage         - complementary color ghosts that bloom and invert

    Everything pulses gently, stays dim and intimate, and uses the warm dark
    palette of closed-eye vision.
    """

    # ---- mode constants ----
    MODE_LATTICE = 0
    MODE_VASCULAR = 1
    MODE_BLUEFIELD = 2
    MODE_AFTERIMAGE = 3
    NUM_MODES = 4

    def __init__(self, led_frame_player=None):
        super().__init__(led_frame_player)

        self.__width = Config.get_or_throw('leds.display_width')
        self.__height = Config.get_or_throw('leds.display_height')

        # Pre-compute coordinate grids (done once, reused every tick)
        y_coords, x_coords = np.mgrid[0:self.__height, 0:self.__width]
        self.__x_grid = x_coords.astype(np.float32)
        self.__y_grid = y_coords.astype(np.float32)
        self.__x_norm = self.__x_grid / max(self.__width, 1)
        self.__y_norm = self.__y_grid / max(self.__height, 1)

        # Center coordinates
        self.__cx = self.__width / 2.0
        self.__cy = self.__height / 2.0

        # Distance from center (used by several modes)
        dx = self.__x_grid - self.__cx
        dy = self.__y_grid - self.__cy
        self.__dist_center = np.sqrt(dx * dx + dy * dy)
        self.__angle_center = np.arctan2(dy, dx)
        self.__max_dist = math.sqrt(self.__cx ** 2 + self.__cy ** 2)

        # Mode state
        self.__mode = 0
        self.__time = 0.0

    # ------------------------------------------------------------------ #
    #  Framework hooks                                                     #
    # ------------------------------------------------------------------ #

    def _setup(self):
        self.__mode = random.randint(0, self.NUM_MODES - 1)
        self.__time = 0.0
        self.__setup_mode()

    def _tick(self):
        dt = 0.025
        self.__time += dt

        frame = np.zeros((self.__height, self.__width, 3), dtype=np.float32)

        if self.__mode == self.MODE_LATTICE:
            self.__tick_lattice(frame)
        elif self.__mode == self.MODE_VASCULAR:
            self.__tick_vascular(frame)
        elif self.__mode == self.MODE_BLUEFIELD:
            self.__tick_bluefield(frame)
        elif self.__mode == self.MODE_AFTERIMAGE:
            self.__tick_afterimage(frame)

        # Global heartbeat breathing -- subtle overall brightness pulse
        heartbeat = 0.92 + 0.08 * math.sin(self.__time * 1.1)
        frame *= heartbeat

        out = np.clip(frame, 0, 255).astype(np.uint8)
        self._led_frame_player.play_frame(out)

    # ------------------------------------------------------------------ #
    #  Per-mode setup                                                      #
    # ------------------------------------------------------------------ #

    def __setup_mode(self):
        """Initialise state specific to the chosen mode."""
        if self.__mode == self.MODE_LATTICE:
            self.__setup_lattice()
        elif self.__mode == self.MODE_VASCULAR:
            self.__setup_vascular()
        elif self.__mode == self.MODE_BLUEFIELD:
            self.__setup_bluefield()
        elif self.__mode == self.MODE_AFTERIMAGE:
            self.__setup_afterimage()

    # ================================================================== #
    #  MODE 0 -- Entoptic lattice                                         #
    # ================================================================== #

    def __setup_lattice(self):
        self.__lattice_hex = random.choice([True, False])
        self.__lattice_scale = random.uniform(3.0, 6.0)
        self.__lattice_drift_x = random.uniform(-0.3, 0.3)
        self.__lattice_drift_y = random.uniform(-0.2, 0.2)

    def __tick_lattice(self, frame):
        t = self.__time
        scale = self.__lattice_scale

        warp_x = math.sin(t * 0.25) * 1.5
        warp_y = math.cos(t * 0.2) * 1.2

        sx = self.__x_grid + t * self.__lattice_drift_x * 3.0 + warp_x
        sy = self.__y_grid + t * self.__lattice_drift_y * 3.0 + warp_y

        warp_amount = 0.3 + 0.2 * math.sin(t * 0.35)
        sx = sx + np.sin(self.__y_norm * 4.0 + t * 0.5) * warp_amount
        sy = sy + np.cos(self.__x_norm * 4.0 + t * 0.4) * warp_amount

        if self.__lattice_hex:
            row = np.floor(sy / scale)
            offset = (row % 2) * (scale * 0.5)
            cell_x = (sx + offset) % scale
            cell_y = sy % scale
            dx = cell_x - scale * 0.5
            dy = cell_y - scale * 0.5
            dist_to_center = np.sqrt(dx * dx + dy * dy)
        else:
            angle = math.pi / 4
            cos_a = math.cos(angle)
            sin_a = math.sin(angle)
            rx = sx * cos_a - sy * sin_a
            ry = sx * sin_a + sy * cos_a
            cell_x = rx % scale
            cell_y = ry % scale
            dx = cell_x - scale * 0.5
            dy = cell_y - scale * 0.5
            dist_to_center = np.sqrt(dx * dx + dy * dy)

        norm_dist = dist_to_center / (scale * 0.5)
        edge = np.clip(1.0 - np.abs(norm_dist - 0.85) * 6.0, 0, 1)
        node = np.exp(-dist_to_center * dist_to_center / (scale * 0.15))
        pattern = edge * 0.7 + node * 0.4

        breath = 0.5 + 0.5 * math.sin(t * 0.8)
        pattern *= 0.4 + 0.6 * breath

        palette_t = math.sin(t * 0.12) * 0.5 + 0.5
        r1, g1, b1 = 160, 100, 30
        r2, g2, b2 = 90, 30, 120
        inv = 1.0 - palette_t
        frame[:, :, 0] = pattern * (r1 * palette_t + r2 * inv)
        frame[:, :, 1] = pattern * (g1 * palette_t + g2 * inv)
        frame[:, :, 2] = pattern * (b1 * palette_t + b2 * inv)

    # ================================================================== #
    #  MODE 1 -- Vascular tree (Purkinje tree)                            #
    # ================================================================== #

    def __setup_vascular(self):
        """Generate a branching tree structure using recursive subdivision.

        Stores branches as (x1, y1, x2, y2, thickness) segments. The tree
        slowly grows, pulses, and periodically regrows from a new origin.
        """
        self.__vasc_regrow_interval = random.uniform(12.0, 20.0)
        self.__vasc_last_regrow = 0.0
        # Current and target fields for smooth morphing
        self.__vascular_field = np.zeros((self.__height, self.__width), dtype=np.float32)
        self.__vasc_target_field = np.zeros((self.__height, self.__width), dtype=np.float32)
        self.__vasc_morph_progress = 1.0  # start by generating first tree immediately
        self.__generate_vascular_tree()
        self.__vascular_field = self.__vasc_target_field.copy()

    def __generate_vascular_tree(self):
        """Generate a new random vascular tree and store as target field."""
        self.__branches = []
        ox = self.__cx + random.uniform(-self.__width * 0.2, self.__width * 0.2)
        oy = self.__cy + random.uniform(-self.__height * 0.2, self.__height * 0.2)
        n_main = random.randint(3, 5)
        for i in range(n_main):
            angle = (2 * math.pi * i / n_main) + random.uniform(-0.4, 0.4)
            length = min(self.__width, self.__height) * random.uniform(0.3, 0.55)
            self.__grow_branch(ox, oy, angle, length, thickness=1.8, depth=0, max_depth=4)
        self.__vasc_target_field = self.__compute_branch_field()
        self.__vasc_morph_progress = 0.0

    def __grow_branch(self, x, y, angle, length, thickness, depth, max_depth):
        """Recursively grow a branching structure."""
        if depth > max_depth or length < 1.0:
            return

        ex = x + math.cos(angle) * length
        ey = y + math.sin(angle) * length
        self.__branches.append((x, y, ex, ey, thickness))

        # Two children with some randomness
        n_children = 2 if random.random() < 0.75 else 1
        for _ in range(n_children):
            child_angle = angle + random.uniform(-0.7, 0.7)
            child_length = length * random.uniform(0.5, 0.75)
            child_thick = thickness * 0.7
            self.__grow_branch(ex, ey, child_angle, child_length, child_thick, depth + 1, max_depth)

    def __compute_branch_field(self):
        """Compute a 2D distance field from the branch segments.

        For each pixel, find the minimum distance to any branch segment,
        weighted by branch thickness. Returns a float32 array where higher
        values mean closer to a branch.
        """
        field = np.zeros((self.__height, self.__width), dtype=np.float32)

        for (x1, y1, x2, y2, thickness) in self.__branches:
            # Vectorised point-to-segment distance
            dx_seg = x2 - x1
            dy_seg = y2 - y1
            seg_len_sq = dx_seg * dx_seg + dy_seg * dy_seg
            if seg_len_sq < 0.001:
                continue

            # Parameter t along the segment for each pixel
            t_param = ((self.__x_grid - x1) * dx_seg + (self.__y_grid - y1) * dy_seg) / seg_len_sq
            t_param = np.clip(t_param, 0.0, 1.0)

            # Closest point on segment
            closest_x = x1 + t_param * dx_seg
            closest_y = y1 + t_param * dy_seg

            dist = np.sqrt((self.__x_grid - closest_x) ** 2 + (self.__y_grid - closest_y) ** 2)

            # Soft falloff based on thickness
            contribution = np.exp(-dist / max(thickness, 0.3))
            field = np.maximum(field, contribution)

        return field

    def __tick_vascular(self, frame):
        t = self.__time

        # Periodically regrow the tree from a new origin
        if t - self.__vasc_last_regrow > self.__vasc_regrow_interval:
            self.__vasc_last_regrow = t
            self.__generate_vascular_tree()

        # Morph from current field toward target
        if self.__vasc_morph_progress < 1.0:
            self.__vasc_morph_progress = min(1.0, self.__vasc_morph_progress + 0.008)
            # Smoothstep easing
            p = self.__vasc_morph_progress
            smooth = p * p * (3 - 2 * p)
            self.__vascular_field = (
                self.__vascular_field * (1 - smooth * 0.02) +
                self.__vasc_target_field * (smooth * 0.02)
            )
            # At the end, snap to target
            if self.__vasc_morph_progress >= 1.0:
                self.__vascular_field = self.__vasc_target_field.copy()

        # Pulsing brightness — traveling wave along the branches
        pulse = 0.5 + 0.5 * math.sin(t * 1.3)
        slow_pulse = 0.7 + 0.3 * math.sin(t * 0.4)

        # Distance-based pulse wave (brightness ripples outward from center)
        wave = 0.7 + 0.3 * np.sin(self.__dist_center * 0.8 - t * 2.0)

        brightness = self.__vascular_field * (0.3 + 0.7 * pulse) * slow_pulse * wave

        # Warm, blood-like colour: shifts between dark red/maroon and orange
        hue_shift = math.sin(t * 0.25) * 0.1
        frame[:, :, 0] = brightness * (150 + hue_shift * 80)
        frame[:, :, 1] = brightness * (45 + hue_shift * 40)
        frame[:, :, 2] = brightness * (30 + hue_shift * 25)

        # Dim background glow that breathes
        bg_glow = 0.05 + 0.03 * math.sin(t * 0.6 + 1.0)
        frame[:, :, 0] += bg_glow * 60
        frame[:, :, 1] += bg_glow * 15
        frame[:, :, 2] += bg_glow * 20

    # ================================================================== #
    #  MODE 2 -- Blue field entoptic phenomenon (Scheerer's)              #
    # ================================================================== #

    def __setup_bluefield(self):
        n_particles = random.randint(15, 30)
        self.__bf_particles = []
        for _ in range(n_particles):
            # Each particle follows a curved/sinusoidal path
            self.__bf_particles.append({
                'phase': random.uniform(0, 2 * math.pi),
                'speed': random.uniform(0.8, 2.5),
                'y_base': random.uniform(0, self.__height),
                'x_freq': random.uniform(0.3, 1.0),
                'x_amp': random.uniform(self.__width * 0.1, self.__width * 0.4),
                'x_center': random.uniform(self.__width * 0.2, self.__width * 0.8),
                'brightness': random.uniform(0.7, 1.0),
                'size': random.uniform(0.6, 1.2),
            })
        # Trail buffer: small 2D accumulation buffer that fades each frame
        self.__bf_trail = np.zeros((self.__height, self.__width), dtype=np.float32)

    def __tick_bluefield(self, frame):
        t = self.__time

        # Deep blue background with subtle variation
        bg_pulse = 0.85 + 0.15 * math.sin(t * 0.3)
        frame[:, :, 0] = 5 * bg_pulse
        frame[:, :, 1] = 8 * bg_pulse
        frame[:, :, 2] = 35 * bg_pulse

        # Very subtle blue noise texture -- slight brightness variation
        noise_phase = t * 0.4
        texture = np.sin(self.__x_norm * 7 + noise_phase) * np.cos(self.__y_norm * 5 + noise_phase * 0.7)
        frame[:, :, 2] += (texture * 8 + 8).astype(np.float32)

        # Fade the trail buffer
        self.__bf_trail *= 0.82

        # Update and render particles
        for p in self.__bf_particles:
            # Curved path: x follows a sinusoidal course, y advances linearly
            progress = (t * p['speed'] + p['phase'])
            py = (p['y_base'] + progress * 4.0) % self.__height
            px = p['x_center'] + math.sin(progress * p['x_freq']) * p['x_amp']
            px = px % self.__width

            ix = int(px) % self.__width
            iy = int(py) % self.__height

            # Deposit into trail buffer (soft dot)
            bright = p['brightness'] * (0.7 + 0.3 * math.sin(t * 3.0 + p['phase']))
            radius = p['size']

            # Paint a small soft dot
            r_int = int(math.ceil(radius)) + 1
            for dy in range(-r_int, r_int + 1):
                for dx in range(-r_int, r_int + 1):
                    nx = (ix + dx) % self.__width
                    ny = (iy + dy) % self.__height
                    d = math.sqrt(dx * dx + dy * dy)
                    if d < radius + 0.5:
                        falloff = max(0, 1.0 - d / (radius + 0.5))
                        self.__bf_trail[ny, nx] = min(1.0, self.__bf_trail[ny, nx] + bright * falloff)

        # Render trails as bright white-blue dots on the deep blue field
        trail = self.__bf_trail
        frame[:, :, 0] += trail * 200
        frame[:, :, 1] += trail * 220
        frame[:, :, 2] += trail * 255

    # ================================================================== #
    #  MODE 3 -- Afterimage (complementary colour ghosts)                 #
    # ================================================================== #

    def __setup_afterimage(self):
        # Cycle through shapes that leave afterimage ghosts
        self.__ai_shape_time = 0.0
        self.__ai_cycle_period = random.uniform(4.0, 7.0)
        # Accumulation buffer for the afterimage (RGB float)
        self.__ai_ghost = np.zeros((self.__height, self.__width, 3), dtype=np.float32)
        # Choose shape types
        self.__ai_shapes = ['circle', 'ring', 'bar', 'diamond']

    def __tick_afterimage(self, frame):
        t = self.__time

        # Determine which phase of the cycle we're in
        cycle_pos = (t % self.__ai_cycle_period) / self.__ai_cycle_period
        shape_idx = int(t / self.__ai_cycle_period) % len(self.__ai_shapes)
        shape = self.__ai_shapes[shape_idx]

        # Colour for this cycle -- slowly rotating hue
        hue = (t * 0.06) % 1.0
        r, g, b = self.__hsv_to_rgb_float(hue, 0.8, 1.0)

        # Phase 0-0.5: shape is present (fading in then out)
        # Phase 0.5-1.0: afterimage (complement) appears
        if cycle_pos < 0.5:
            # Shape presence -- bell curve intensity
            intensity = math.sin(cycle_pos * math.pi) * 0.8

            shape_mask = self.__make_shape(shape, t)
            frame[:, :, 0] += shape_mask * r * intensity * 150
            frame[:, :, 1] += shape_mask * g * intensity * 150
            frame[:, :, 2] += shape_mask * b * intensity * 150

            # Accumulate into ghost buffer (the stimulus)
            self.__ai_ghost[:, :, 0] += shape_mask * r * intensity * 4.0
            self.__ai_ghost[:, :, 1] += shape_mask * g * intensity * 4.0
            self.__ai_ghost[:, :, 2] += shape_mask * b * intensity * 4.0
        else:
            # Afterimage phase: show the complement of accumulated ghost
            ghost_phase = (cycle_pos - 0.5) * 2.0  # 0..1 within ghost phase
            ghost_intensity = math.sin(ghost_phase * math.pi) * 0.6

            # Complement: invert the accumulated colour
            ghost_max = np.maximum(self.__ai_ghost.max(), 1.0)
            complement = 1.0 - (self.__ai_ghost / ghost_max)

            frame[:, :, 0] += complement[:, :, 0] * ghost_intensity * 100
            frame[:, :, 1] += complement[:, :, 1] * ghost_intensity * 100
            frame[:, :, 2] += complement[:, :, 2] * ghost_intensity * 100

        # Decay the ghost buffer
        self.__ai_ghost *= 0.96

        # Very dim warm background glow
        bg = 0.03 + 0.02 * math.sin(t * 0.5)
        frame[:, :, 0] += bg * 80
        frame[:, :, 1] += bg * 30
        frame[:, :, 2] += bg * 40

    def __make_shape(self, shape, t):
        """Return a float32 mask (0-1) for the given shape type."""
        # Gentle pulsing size
        pulse = 0.8 + 0.2 * math.sin(t * 1.5)
        base_size = min(self.__width, self.__height) * 0.3 * pulse

        if shape == 'circle':
            return np.clip(1.0 - self.__dist_center / max(base_size, 1), 0, 1)

        elif shape == 'ring':
            ring_dist = np.abs(self.__dist_center - base_size * 0.7)
            thickness = base_size * 0.2
            return np.clip(1.0 - ring_dist / max(thickness, 0.5), 0, 1)

        elif shape == 'bar':
            angle = t * 0.3
            # Project pixel positions onto the bar's perpendicular axis
            perp_dist = np.abs(
                (self.__x_grid - self.__cx) * math.sin(angle) -
                (self.__y_grid - self.__cy) * math.cos(angle)
            )
            bar_width = base_size * 0.2
            along_dist = np.abs(
                (self.__x_grid - self.__cx) * math.cos(angle) +
                (self.__y_grid - self.__cy) * math.sin(angle)
            )
            mask = np.clip(1.0 - perp_dist / max(bar_width, 0.5), 0, 1)
            mask *= np.clip(1.0 - along_dist / max(base_size, 1), 0, 1)
            return mask

        elif shape == 'diamond':
            dx = np.abs(self.__x_grid - self.__cx)
            dy = np.abs(self.__y_grid - self.__cy)
            diamond_dist = dx + dy
            return np.clip(1.0 - diamond_dist / max(base_size * 1.2, 1), 0, 1)

        return np.zeros((self.__height, self.__width), dtype=np.float32)

    # ------------------------------------------------------------------ #
    #  Colour helpers                                                      #
    # ------------------------------------------------------------------ #

    def __hsv_to_rgb_float(self, h, s, v):
        """Single HSV to RGB, returns (r, g, b) floats in 0-1."""
        if s == 0.0:
            return (v, v, v)
        i = int(h * 6.0)
        f = (h * 6.0) - i
        p = v * (1.0 - s)
        q = v * (1.0 - s * f)
        t = v * (1.0 - s * (1.0 - f))
        i %= 6
        if i == 0:
            return (v, t, p)
        elif i == 1:
            return (q, v, p)
        elif i == 2:
            return (p, v, t)
        elif i == 3:
            return (p, q, v)
        elif i == 4:
            return (t, p, v)
        else:
            return (v, p, q)

    # ------------------------------------------------------------------ #
    #  Class metadata                                                      #
    # ------------------------------------------------------------------ #

    @classmethod
    def get_id(cls) -> str:
        return 'purkinje'

    @classmethod
    def get_name(cls) -> str:
        return 'Purkinje'

    @classmethod
    def get_description(cls) -> str:
        return 'Phosphenes, afterimages, and entoptic patterns from closed-eye vision'
