#!/usr/bin/env python3
import argparse
import os
import sys

# This is necessary for the import below to work
root_dir = os.path.abspath(os.path.dirname(__file__) + '/..')
sys.path.append(root_dir)

from pifi.config import Config
from pifi.logger import Logger
from pifi.video.videoprocessor import VideoProcessor

def parse_args():
    parser = argparse.ArgumentParser(description="Download a video from youtube and save it to disk. The video " +
        "will be formatted in the proper resolution and codec necessary for playback.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--url', dest='url', action='store', required = True,
        help='youtube video url')
    parser.add_argument('--output-file', dest='output_file', action='store', required = True,
        help='output file without file extension')
    args = parser.parse_args()
    return args

def main():
    args = parse_args()
    Config.load_config_if_not_loaded()
    (VideoProcessor(url = args.url, clear_screen = False, show_loading_screen = False)
        .download_video(args.output_file + VideoProcessor.DEFAULT_VIDEO_EXTENSION))


main()
