#!/usr/bin/env python3
import argparse
import os
import sys

# This is necessary for the import below to work
root_dir = os.path.abspath(os.path.dirname(__file__) + '/..')
sys.path.append(root_dir)

from pifi.config import Config
from pifi.logger import Logger

def parse_args():
    parser = argparse.ArgumentParser(description=
f"""This is called in the install/install_dependencies.sh script.
This script prints out the specified config values as they are set in the config file {Config.CONFIG_PATH}.
""",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--keys', dest='keys', action='store', default='',
        help="Comma separated list of keys. Each key should be in dot notation. We will print the " +
        "corresponding values of these keys, or a blank line if the key is not set.")
    args = parser.parse_args()
    return args

def main():
    args = parse_args()

    Logger.set_level(Logger.QUIET) # silence any other output to stdout, because we parse this script's stdout output.
    Config.load_config_if_not_loaded(should_set_log_level = False)

    config_keys_to_print = args.keys.split(',')
    for key in config_keys_to_print:
        print(Config.get(key, ''))


main()
