#!/usr/bin/python3
# This is called in the ./install/install.sh script
import os
import sys

# This is necessary for the import below to work
root_dir = os.path.abspath(os.path.dirname(__file__) + '/..')
sys.path.append(root_dir)

from pifi.database import Database
Database().construct()
