#!/usr/bin/env python3
import argparse
import os
import sys

# This is necessary for the import below to work
root_dir = os.path.abspath(os.path.dirname(__file__) + '/..')
sys.path.append(root_dir)

from pifi.settingsdb import SettingsDb

def parseArgs():
    parser = argparse.ArgumentParser(
        description=('Set the youtube API key used by the front end. ' +
            'If called with no arguments, print the current youtube API key (if any).'),
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    parser.add_argument('--api-key', dest='api_key', action='store',
        help='The youtube api key to set')
    args = parser.parse_args()
    return args


args = parseArgs()
settings_db = SettingsDb()

if args.api_key is None:
    api_key = settings_db.get(SettingsDb.SETTING_YOUTUBE_API_KEY)
    if api_key is None:
        print("No youtube API key found.", file = sys.stderr)
    else:
        print(str(api_key))
else:
    success = settings_db.set(SettingsDb.SETTING_YOUTUBE_API_KEY, args.api_key)
    if not success:
        raise Exception(f"Unable to set youtube api key to: {args.api_key}")
    else:
        print(f"Successfully set youtube api key to: {args.api_key}")
